/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { motion, useViewportScroll } from "framer-motion";
import HomePage from "../components/HomePage";
import NavBar from "../components/NavBar";
import { useRouter } from "next/router";

function Home() {
  const { scrollYProgress } = useViewportScroll();
  const router = useRouter();

  return (
    <motion.path
      d="M 0, 20 a 20, 20 0 1,0 40,0 a 20, 20 0 1,0 -40,0"
      style={{ pathLength: scrollYProgress }}
    >
      <div className="bg-stone-800">
        <Head>
          <title>B2B Cabs</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/main.png" />
        </Head>

        <main className="h-full bg-stone-800 scroll-smooth">
          <NavBar />
          <HomePage />
        </main>
      </div>
    </motion.path>
  );
}

export default Home;